name: Contract Audit

on:
  pull_request:
    branches:
      - release/**
    paths:
      - 'contracts/**'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup Virtual Environment
        run: |
          pip install virtualenv
          python -m virtualenv venv
      - name: Install MythX
        run: |
          source venv/bin/activate
          pip install mythx-cli
      - name: Analyze
        env:
          MYTHX_API_KEY: ${{ secrets.MYTHX_API_KEY }}
        run: |
          source venv/bin/activate
          mythx --ci --yes analyze contracts/**/*.sol \
            --solc-version 0.8.17 \
            --mode standard \
            --remap-import "@openzeppelin/=./node_modules/@openzeppelin/"
