name: Solidity CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.ts"
      - "contracts/**"
      - ".github/workflows/pr.yml"
      - "**.json"
      - "**.yaml"

env:
  ALCHEMY_API_URL: ${{ secrets.ALCHEMY_API_URL }}
  ADDRESS_PRIVATE_KEY: ${{ secrets.ADDRESS_PRIVATE_KEY }}
  STAGE: dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint

  compile:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v2
      - name: Compile

  test:
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - uses: actions/checkout@v2
      - name: Test
